### PR TITLE
Art Pass Proposal

### PR DESCRIPTION
**Pull request by HiggsBonbon**
Added new graphics. Skipped rutile as it is irrelevant with Titanium ore, I suggest dropping support and collaborating to have it removed from other mods.

If accepted, I will begin art passes for NetherMetals and will potentially work on CTM integration and [Ore Stones Replacements](https://minecraft.curseforge.com/projects/ore-stone-variants) support.

### CODE REVIEW

**Comment by jriwanek** [comment]
Well, for starters you'd actually have to open a PR to the correct repository, instead of your Fork, I disagree with your POV on Rutile btw, we're about choice, not politics.

**Comment by HiggsBonbon** [comment]
Woah woah woah okay, cut the hostility, I'm trying to help here.

**Comment by jriwanek** [comment]
What hostility?
You still need to open the PR against the correct repo btw.

**Comment by dshadowwolf** [comment]
1) If you want your PR accepted into the actual codebase of the mod, you have to PR against the "MinecraftModDevelopment" repo and not your fork
2) Rutile is included for people that want the extra step to producing Titanium - the *Metals mods are about providing choice for pack-makers and players
3) What hostility ?

**Pull request closed without merging**
